// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3AoEoNlTHIcNmXyUsAy_k1sy8YkkHrsg',
    appId: '1:854997401829:android:89e5eacea4f18a0e0fd40c',
    messagingSenderId: '854997401829',
    projectId: 'tramitesabogados-a6638',
    storageBucket: 'tramitesabogados-a6638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApbYVeoYjLkCdrjyXcqV1HquRrPpS3wYI',
    appId: '1:854997401829:ios:968c167a138b9cef0fd40c',
    messagingSenderId: '854997401829',
    projectId: 'tramitesabogados-a6638',
    storageBucket: 'tramitesabogados-a6638.appspot.com',
    androidClientId: '854997401829-virntihgr79bpaltjv78hjv8as2uqp77.apps.googleusercontent.com',
    iosClientId: '854997401829-q49vnkpj40l52846n9fav0j6k6gm7mv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tramitesApp',
  );
}
